#!/bin/bash
LOG_FILE=brainfish_`date +%Y-%m-%dT%H_%M_%S`.log
log_with_timestamp.py $LOG_FILE | WINEARCH=win64 WINEPREFIX=/path_to/.wine64 wine64 /path_to/BrainFish_160724_modern/BrainFish_160724_modern.exe | log_with_timestamp.py $LOG_FILE
