#!/bin/bash
if [ -e log_prefix ]
then
  LOG_PREFIX=`cat log_prefix`_
fi
LOG_FILE=${LOG_PREFIX}`date +%Y-%m-%dT%H_%M_%S`.log
log_with_timestamp.py $LOG_FILE | stockfish | log_with_timestamp.py $LOG_FILE
